  # Comments in GraphQL are defined with the hash (#) symbol.

  # This "Book" type can be used in other type declarations.
  """
  # Book type
  
  Testing GraphQL markdown documentation. The **Book** type defines 
  books in our schema. Books can have *title's* and *author's*.
  """
  type Book {
    title: String
    author: String
  }

  # The "Query" type is the root of all GraphQL queries.
  # (A "Mutation" type will be covered later on.)
  type Query {
    books: [Book]
  }